### ISSUE TITLE
How can i configure this plugin to work with Siteground's hosting?

### ISSUE THREAD

**Issue by jazir5** [palasthotel/use-memcached#3]
Hi, i use Siteground for hosting and have found that their SG Optimizer plugin is subpar. It adds a ton of overhead, so enabling it solely for memcached is not an option(it slows the site down having it active). I currently utilize WP-Rocket in concert with Asset Cleanup and Cloudflare for caching. Can i add your plugin to my current caching solutions for improved performance? If so, can you tell me what info specifically needs to be plugged in the wp-config file?

**Comment by EdwardBock** [comment]
Hi @jazir5 

sorry for not answering. I hove you found a good solution for your project.

We are not maintaining this anymore, so close!
