### ISSUE TITLE
Warning after activation: Could not find use_memcached function. Memcached class not exists!

### ISSUE THREAD

**Issue by iceblink3** [palasthotel/use-memcached#4]
WP 5.7.2 on PHP7.4 + Apache 2.4.5
Copied object-cache.php to /wp-content, memcached is installed and appears to be working (see details below).

After activation, a warning/error appears:
Use Memcached
Could not find use_memcached function.
Memcached class not exists!

  [ Memcache is enabled. Disable memcached!]

We do not have Freistil infrastructure
Freistil prefix:
Global prefix:
Blog prefix: 

=========================
# memcstat --servers=localhost

Server: localhost (11211)
	 pid: 11700
	 uptime: 3391
	 time: 1622616386
	 version: 1.4.33
	 libevent: 2.0.21-stable
	 pointer_size: 64
	 rusage_user: 0.108000
	 rusage_system: 0.844000
	 curr_connections: 1
	 total_connections: 23
	 connection_structures: 11
	 reserved_fds: 20
	 cmd_get: 2867
	 cmd_set: 268
	 cmd_flush: 0
	 cmd_touch: 0
	 get_hits: 2221
	 get_misses: 646
	 get_expired: 0
	 get_flushed: 0
	 delete_misses: 4
	 delete_hits: 5
	 incr_misses: 0
	 incr_hits: 2
	 decr_misses: 0
	 decr_hits: 0
	 cas_misses: 0
	 cas_hits: 0
	 cas_badval: 0
	 touch_hits: 0
	 touch_misses: 0
	 auth_cmds: 0
	 auth_errors: 0
	 bytes_read: 2626415
	 bytes_written: 15002158
	 limit_maxbytes: 67108864
	 accepting_conns: 1
	 listen_disabled_num: 0
	 time_in_listen_disabled_us: 0
	 threads: 4
	 conn_yields: 0
	 hash_power_level: 16
	 hash_bytes: 524288
	 hash_is_expanding: 0
	 malloc_fails: 0
	 log_worker_dropped: 0
	 log_worker_written: 0
	 log_watcher_skipped: 0
	 log_watcher_sent: 0
	 bytes: 652850
	 curr_items: 170
	 total_items: 268
	 expired_unfetched: 0
	 evicted_unfetched: 0
	 evictions: 0
	 reclaimed: 0
	 crawler_reclaimed: 0
	 crawler_items_checked: 0
	 lrutail_reflocked: 0

**Comment by EdwardBock** [comment]
Sorry for not answering @iceblink3 . We are not maintaining this plugin anymore. I hope you found a good alternative solution.
