### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by Dudematters** [palasthotel/use-memcached#5]
I cannot seem to find the documentation on the possible settings in wp-config.php.
Would like to see a bit more options in a wp interface?

**Comment by robwoodgate** [comment]
An important setting to highlight is the WP_CACHE_KEY_SALT constant.
This is set to 'salt-and-pepper' by default, which can cause pollution where a server hosts multiple WP installs.

Would recommend this is set to a better default too - e.g. in /templates/object-cache.php Line 164:
`define( 'WP_CACHE_KEY_SALT', sha1( get_site_url() ) );`

**Comment by kevin25** [comment]
This plugin seemed to be dead

**Comment by EdwardBock** [comment]
@robwoodgate nice suggestions.

@kevin25 Yes, it is. Please accept our apologies. We no longer use or maintain this plugin.
